apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chatbot-app-data-pvc
  labels:
    app: devops-chatbot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chatbot-frontend-pvc
  labels:
    app: devops-chatbot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: standard
