apiVersion: v1
kind: Service
metadata:
  name: devops-chatbot-service
  labels:
    app: devops-chatbot
spec:
  type: NodePort
  ports:
  - port: 8002
    targetPort: 8002
    nodePort: 30080  # Accessible via <minikube-ip>:30080
    protocol: TCP
    name: http
  selector:
    app: devops-chatbot
---
apiVersion: v1
kind: Service
metadata:
  name: devops-chatbot-loadbalancer
  labels:
    app: devops-chatbot
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8002
    protocol: TCP
    name: http
  selector:
    app: devops-chatbot
